### ISSUE TITLE
Manpads and MATs

### ISSUE THREAD

**Issue by QuintusGARS** [Sniperhid/tmf_1tac_loadouts#5]
Us Cold war loadout (woodland M81) has some broken slots: AA missile specialist and missile assistant don't get any backpack or RHS stinger missiles, either loaded in the launcher or in reserve.

MAT specialist and assistant don't get any CUP Dragon missile, either loaded or in their backpacks; this might be because the missile is really heavy and it exceedes maximum weight for soldier or maximus space for the backpack. Had a similar issue with loadouts for the old F3 format.

Both launchers are present though, and everything else seems fine. I get this error in the autotest.
https://cdn.discordapp.com/attachments/98548479864885248/219142455155490816/20160827191138_1.jpg

**Comment by Sniperhid** [comment]
Done.
